sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FVFFwP47WdOSIadNT83K8uXNCeKXT6bDi3GLlf8vyRIa5KaKm0UuUqtYWH6PcVFxPrl32R2nlmzg5PbDOFM9d5Cyz5TZEchL7Pt0uY+M5hNe120KpL5ictNbmQ+/kr6LBVA9jFifCb0OO332YSmCosODmTDrMGzNoiNCejmw1rKC8uHuzNKwsmTL5JLg61jHBfzY6347A7UDgKPpUucO1Z63jyCnPk6IbQV9DN18PtdseZ3hQpzowCpnUN34bgqRkR+/NRH/KK6nFC2bPUzRVhP/Zd/ytDZ2Cht8qF+dfHH51tvTnKgS4LN7ELlF3iuQUl0F+JwECRqvTCHVFoYu5085k75g+PVI4jZh8+F7zai5vBxJh9UR0LJLhJ34JIeMZIFNu3cV01ifRcpmkWZnP4GJpmTCD3FBX+goewYbkA6obg3ZQ8yK4aejrENusP4grKKxeJIjn8eAs5PvEU5exTvHhZ/nhXyHMZ+vMypCh/EpP5QZ6Bdbmqn02kEMBL8iXqFbhBYzEiVM2eix1XwGJgn/bpf3IktSIgpEeBmRRkXw9bQM1bDV8C5jFUJh3NS1aoLnpQUU6O+h1RJ3xf12zUbQ3kD5rUeYXg4Okn+ISdTixSGPhsRWOwHDLWRVgScIK8hJDmdbyF44m57M1FR5Mtnmpg13FjeWxpZYi2jABXA=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Phaedrus_1636
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy